app_test/urls.py
from django.urls import path
from .views import AppViewIdx, AppViewPage01
from . import views

app_name = 'app_name_01'

urlpatterns = [
    path('ns_idx/',
         AppViewIdx.as_view(template_name='app_test/index.html'),
         name='name_idx'),
    path('ns_pg01/',
         AppViewPage01.as_view(template_name='app_test/page01.html'),
         name='name_pg01'),
    path('', views.post_list, name='post_list'),
]

testWebApp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('path01/', include('app_test.urls')),
    path('', include('app_test.urls')),
]

app_test/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

app_test/views.py
from django.views.generic.base import TemplateView
from django.shortcuts import render
from django.utils import timezone
from .models import Post


class AppViewIdx(TemplateView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["app"] = "Index"
        return context


class AppViewPage01(TemplateView):

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["app"] = "Page01"
        return context

def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('published_date')
    return render(request, 'app_test/post_list.html', {'posts': posts})

templates/app_test/index.html
<!DOCTYPE html>
<html>
 <head>
 <title>{{app}}ページだよ♪</title>
 </head>
 <body>
 <p>ここは、＜{{app}}＞です.</p>
 </body>
 <a href="{% url 'app_name_01:name_pg01' %}">Page01へのリンクだよ</a>
</html>

templates/app_test/page01.html
<!DOCTYPE html>
<html>
 <head>
 <title>{{app}}だよ♪</title>
 </head>
 <body>
 <p>ここは、＜{{app}}＞です.</p>
 </body>
 <a href="{% url 'app_name_01:name_idx' %}">Indexへのリンクだよ</a>
</html>

templates/app_test/post_list.html
<!DOCTYPE html>
<html>
    <head>
        <title>Django Girls blog</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Django Girls Blog</a></h1>
        </div>

        {% for post in posts %}
        	<div>
        		<p>published: {{ post.published_date }}</p>
        		<h2><a href="">{{ post.text|linebreaksbr }}</a></h2>
             </div>
        {% endfor %}

    </body>
</html>